############################# English ############################
[en]
languageName = "English"
title = "DreamDO Career"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Support"
#footer_menu_right = "Support"
footer_content = "We help you _DO_ what it takes to land your dream career."
# copyright
copyright = "Copyright &copy; 2023 DreamDO Career"



############################# Japanese ############################
[ja]
languageName = "日本語"
title = "DreamDO Career"
contentDir = "content/japanese"
weight = 2
########### footer content ##########
footer_menu_left = "企業情報"
footer_menu_middle = "サポート"
#footer_menu_right = "Support"
footer_content = "海外で働く夢に向かって努力する学生の_DO_をサポートします"
# copyright
copyright = "Copyright &copy; 2023 DreamDO Career"
