############################# English ############################
[en]
languageName = "English"
title = "DreamDo Career"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "We help you DO what it takes to land your dream career."
# copyright
copyright = "Copyright &copy; 2023 DreamDO Career"



############################# Deutsch ############################
[de]
languageName = "日本語"
title = "DreamDo Career"
contentDir = "content/deutsch" # content/german
weight = 2
########### footer content ##########
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
copyright = "Design von [Themefisher](https://themefisher.com/) Entwickelt von [Gethugothemes](https://gethugothemes.com/)"