# main menu
[[main]]
name = "会社概要"
url = "about-us/"
weight = 1

[[main]]
name = "サービス一覧"
url = "our-services/"
weight = 2

#[[main]]
#name = "Blog"
#url = "blog/"
#weight = 2

#[[main]]
#name = "Pricing"
#url = "pricing/"
#weight = 3

[[main]]
name = "お問い合わせ"
url = "contact/"
weight = 4

#[[main]]
#name = "FAQ"
#url = "faq/"
#weight = 5

# footer menu left
[[footer_left]]
name = "会社概要"
url = "about-us/"
weight = 1

[[footer_left]]
name = "サービス一覧"
url = "our-services/"
weight = 2

#[[footer_left]]
#name = "Pricing"
#url = "pricing/"


# footer menu middle
#[[footer_middle]]
#name = "プライバシーポリシー"
#url = "privacy-policy/"

#[[footer_middle]]
#name = "利用規約"
#url = "terms-conditions/"

#[[footer_middle]]
#name = "よくあるご質問"
#url = "faq/"

# footer menu right
#[[footer_right]]
#name = "Privacy Policy"
#url = "privacy-policy/"

#[[footer_right]]
#name = "Terms & Conditions"
#url = "terms-conditions/"

#[[footer_right]]
#name = "FAQ"
#url = "faq/"
